共通ボタンのスタイリングを変更
qin-spring-development/spring-of-engivia pull request #26
Opened 2021-11-11 04:32 UTC by mu0363

## 変更の概要

- 変更の概要
- 共通ボタンのスタイリングを変更
- [jira](https://qinspringdevelopment.atlassian.net/browse/EGI-17)

## なぜこの変更をするのか

- 複数箇所で使用するボタンを共通化し、変更を容易に反映するため

## やったこと

- [x] src/components/Button.tsxに`primary` propsを追加し、booleanでプライマリーボタンかどうかを選べる

## 変更内容

<img width="848" alt="CleanShot 2021-11-11 at 13 30 20@2x" src="https://user-images.githubusercontent.com/15007672/141237353-33dbf29e-67d9-44eb-80ba-66b20a73e7d3.png">

## 影響範囲
ボタン使用画面

2021-11-11 14:21 UTC, shogo4131 requested changes
レビュー記載しました！
ご確認お願い致します👍

2021-11-11 14:21 UTC, shogo4131 commented on src/components/Button/index.tsx
>  export interface Props {
自分がサンプルで書いていたものなのですが今回のプロジェクトではtypeを使用しているので
`export  type  Props = {}`に変更お願いします🙏

2021-11-11 14:21 UTC, shogo4131 commented on src/components/Button/index.tsx
> +  primary: boolean;
[真偽値の変数命名](https://kusamakura.hatenablog.com/entry/2016/03/03/boolean_%E5%80%A4%E3%82%92%E8%BF%94%E5%8D%B4%E3%81%99%E3%82%8B%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E5%90%8D%E3%80%81%E5%A4%89%E6%95%B0%E5%90%8D%E3%81%AE%E4%BB%98%E3%81%91%E6%96%B9)
これを参考にしてprimaryの変数命名を修正してみてください！！

2021-11-11 14:21 UTC, shogo4131 commented on src/components/Button/index.tsx
> +        disabled={isSubmitting}
ボタンをmargin等で移動したい場合があるので、PropsにclassNameを追加し、ボタン内のclassNameに値を追加しておいてください。

2021-11-12 02:07 UTC, mu0363 commented
@shogo4131 
もろもろ修正しました〜
真偽値の変数命名のリンクありがとうございます！

2021-11-12 04:40 UTC, shogo4131 commented
@mu0363 
修正確認しました！
自分がサンプルで書いてたところまで
ありがとうございます！
マージ大丈夫です🙆‍♂️

2021-11-12 07:20 UTC, shogo4131 approved these changes

2021-11-12 07:23 UTC, mu0363 commented
@shogo4131 
ご確認ありがとうございます！マージします〜

2021-11-12 07:23 UTC, merged